[research] Remove x2vlm dependency due to package breakage (#2929)
Summary: The x2vlm package dependencies installs some shared objects
that break the python base image.

Specifically, when you try to import cv2, I kept getting this error:
```
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
```

Rather than diagnose and address the problem, I've decided to remove the
change and point users to the correct PRs to re-run the benchmark for
x2vlm, since x2vlm wasn't the model we decided to go with after the
benchmark.
I discovered this while doing a git bisect.

Relevant Issues: n/a

Type of change: /kind bugfix

Test Plan: Ensured that the python base image could run again after
removing x2vlm

---------

Signed-off-by: Phillip Kuznetsov <philkuz@gimletlabs.ai>
GitOrigin-RevId: 2ce2298adc3d3e66fbb6e7d52450db9fca34ce39